// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAojQaJ7CrSq_YvSoVVpfoIJ6rweuOha5o',
    appId: '1:834620480229:web:bb9dc9b4c5db01caacd20c',
    messagingSenderId: '834620480229',
    projectId: 'cafe-aux-donnees-fb13a',
    authDomain: 'cafe-aux-donnees-fb13a.firebaseapp.com',
    storageBucket: 'cafe-aux-donnees-fb13a.firebasestorage.app',
    measurementId: 'G-3JHXSKN6R9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_PmsNB3VzJ1g34dfm_iAK6xzPYos0HSQ',
    appId: '1:834620480229:android:7e9c4c3d14a6131dacd20c',
    messagingSenderId: '834620480229',
    projectId: 'cafe-aux-donnees-fb13a',
    storageBucket: 'cafe-aux-donnees-fb13a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACvwgsZXVH5iE65P8GbtAElWRlIK0Q45c',
    appId: '1:834620480229:ios:26b54e1eb2c812ccacd20c',
    messagingSenderId: '834620480229',
    projectId: 'cafe-aux-donnees-fb13a',
    storageBucket: 'cafe-aux-donnees-fb13a.firebasestorage.app',
    iosBundleId: 'com.example.cafeAuxDonnees',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACvwgsZXVH5iE65P8GbtAElWRlIK0Q45c',
    appId: '1:834620480229:ios:26b54e1eb2c812ccacd20c',
    messagingSenderId: '834620480229',
    projectId: 'cafe-aux-donnees-fb13a',
    storageBucket: 'cafe-aux-donnees-fb13a.firebasestorage.app',
    iosBundleId: 'com.example.cafeAuxDonnees',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAojQaJ7CrSq_YvSoVVpfoIJ6rweuOha5o',
    appId: '1:834620480229:web:854c3650482ce728acd20c',
    messagingSenderId: '834620480229',
    projectId: 'cafe-aux-donnees-fb13a',
    authDomain: 'cafe-aux-donnees-fb13a.firebaseapp.com',
    storageBucket: 'cafe-aux-donnees-fb13a.firebasestorage.app',
    measurementId: 'G-2N3E73Q1F1',
  );
}
